{
  constants {
    heroes {
      id
      name
      aliases
      roles {
        roleId
        level
      }
      displayName
      shortName
      stats {
        primaryAttribute
      }
    }
  }
}
