{
  live {
    matches(
      request: {
        skip: 0
        take: 1000
        tiers: [
          PROFESSIONAL
          AMATEUR
          MINOR
          MAJOR
          INTERNATIONAL
          DPC_QUALIFIER
          DPC_LEAGUE_QUALIFIER
          DPC_LEAGUE
          DPC_LEAGUE_FINALS
        ]
        isCompleted: false
      }
    ) {
      matchId
      league {
        id
        name
        displayName
        basePrizePool
        prizePool

        tier
      }
      radiantScore
      direScore
      delay
      spectators
      averageRank
      radiantLead
      lobbyType
      serverSteamId
      gameTime
      completed
      radiantTeamId
      direTeamId
      gameMode
      gameState
      gameMinute
      players {
        heroId
        name
        steamAccountId
        isRadiant
        position
        numLastHits
        networth
        steamAccount {
          profileUri
          avatar
          proSteamAccount {
            name
            realName
            romanizedRealName
            isPro
            roles
            signatureHeroes
          }
        }
      }
      playbackData {
        pickBans {
          isPick
          heroId
          order
          bannedHeroId
          isRadiant
          baseWinRate
          adjustedWinRate
          position
        }
      }
      gameState
      gameMinute
      radiantTeam {
        id
        name
        tag
        dateCreated
        isPro
        isLocked
        countryCode
        url
        logo
        baseLogo
        bannerLogo
        winCount
        lossCount
        lastMatchDateTime
        countryName
      }
      direTeam {
        id
        name
        tag
        dateCreated
        isPro
        isLocked
        countryCode
        url
        logo
        baseLogo
        bannerLogo
        winCount
        lossCount
        lastMatchDateTime
        countryName
      }
    }
  }
}
